apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mqtt-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mqtt-exporter
  endpoints:
  - port: exporter
    path: /
