FROM node:18

WORKDIR /b_end
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh ./
# package 복사, 또 뭐필요하지
COPY package*.json ./
RUN npm install & chmod +x wait-for-it.sh
COPY . .
RUN npm run build
#RUN npx prisma migrate deploy

EXPOSE 3000

CMD ["bash", "-c", "./wait-for-it.sh database:5432 -t 60 -- npx prisma migrate deploy && npm run start:prod"]
