apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: server
  namespace: monitoring
spec:
  replicas: 1
  alertmanagerConfigNamespaceSelector: {}
  alertmanagerConfigSelector:
    matchLabels:
      alert: humid
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: humid-config
  labels:
    alert: humid
spec:
  receivers:
    - name: telegram
      telegramConfigs:
        - chatID: -1001996796672
          botToken:
            name: telegram
            key: token
          sendResolved: true
  route:
    groupBy:
      - humid
    groupWait: 5s
    groupInterval: 5s
    repeatInterval: 15m
    receiver: telegram
