version: '3.8'

services:
  backend:
    build: ./b_end
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./b_end:/usr/src/app
    depends_on:
      - mongo

  frontend:
    build: ./f_end
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./f_end:/usr/src/app

  database:
    image: postgres:13
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  mosquitto:
    build: ./mosqt
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

volumes:
  db-data:
