version: '3.8'

services:
  backend:
    build: ./b_end
    container_name: backend
    restart: always
    volumes:
      - ./b_end:/usr/src/app
      - statics:/usr/src/app/uploads
    depends_on:
      - mongo
      - database
      - mosquitto
    env_file:
      - .env.dev

  frontend:
    build: ./f_end
    container_name: frontend
    restart: always
    volumes:
      - ./f_end:/usr/src/app
    env_file:
      - .env.dev

  database:
    image: postgres:13
    container_name: database
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mosquitto:
    build: ./mosqt
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - statics:/usr/share/nginx/static

  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

volumes:
  db-data:
  statics:
