version: '3.8'

services:
  backend:
    build: ./b_end
    container_name: backend
    restart: always
    volumes:
      - statics:/b_end/uploads
    depends_on:
      - mongo
      - database
      - mosquitto
    env_file:
      - .env

  frontend:
    build: ./f_end
    container_name: frontend
    volumes:
      - html:/f_end/dist
    env_file:
      - .env

  database:
    image: postgres:13
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - statics:/usr/share/nginx/static
      - html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt

  mosquitto:
    build: ./mosqt
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"

  mongo:
    build: ./mongo
    container_name: mongo
    restart: always

volumes:
  db-data:
  statics:
  html:
