apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-exporter
  template:
    metadata:
      labels:
        app: mqtt-exporter
    spec:
      containers:
      - name: mqtt-exporter
        image: kpetrem/mqtt-exporter
        env:
        - name: MQTT_ADDRESS
          value: "mqtt-broker-svc"
        - name: MQTT_PORT
          value: "1883"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
spec:
  selector:
    app: mqtt-exporter
  ports:
  - name: exporter
    protocol: TCP
    port: 9000
    targetPort: 9000
