name: CD workflows

on:
  pull_request:
    types:
      - closed
    branches:
      - release
  push:
    branches:
      - release

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SCP to GCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.GCP_IP }}
        username: ${{ secrets.GCP_ID }}
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "."
        target: "/home/${{ secrets.GCP_ID }}/A-"

    - name: Deploy(docker-compose)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_IP }}
        username: ${{ secrets.GCP_ID }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          cd /home/${{ secrets.GCP_ID }}/A-
          docker-compose -f prod.docker-compose.yml down && docker volume rm a-_html
          docker-compose -f prod.docker-compose.yml up --build -d
